export interface StravaActivity {
  id: number;
  name: string;
  distance: number;
  moving_time: number;
  elapsed_time: number;
  total_elevation_gain: number;
  type: string;
  sport_type?: string;
  start_date: string;
  timezone: string;
  start_latlng: any;
  end_latlng: any;
  achievement_count: number;
  kudos_count: number;
  comment_count: number;
  athlete_count: number;
  photo_count: number;
  map: any;
  trainer: boolean;
  commute: boolean;
  manual: boolean;
  private: boolean;
  flagged: boolean;
  workout_type: number;
  upload_id: number;
  average_speed: number;
  max_speed: number;
  has_heartrate: boolean;
  average_heartrate: number;
  max_heartrate: number;
  heartrate_opt_out: boolean;
  display_hide_heartrate_option: boolean;
  elev_high: number;
  elev_low: number;
  pr_count: number;
  total_photo_count: number;
  has_kudoed: boolean;
  suffer_score: number;
  description: string;
  calories: number;
  segment_efforts?: StravaSegment[];
  device_name?: string;
  embed_token?: string;
  splits_metric?: any;
  splits_standard?: any;
  laps?: any[];
  gear_id?: string;
  average_cadence?: number;
  average_temp?: number;
  average_watts?: number;
  weighted_average_watts?: number;
  kilojoules?: number;
  device_watts?: boolean;
  has_power_meter?: boolean;
  max_watts?: number;
  perceived_exertion?: number;
  prefer_perceived_exertion?: boolean;
  segment_leaderboard_opt_out?: boolean;
}

export interface StravaSegment {
  id: number;
  name: string;
  elapsed_time: number;
  moving_time: number;
  start_date: string;
  distance: number;
  start_index: number;
  end_index: number;
  average_cadence?: number;
  average_watts?: number;
  device_watts?: boolean;
  average_heartrate?: number;
  max_heartrate?: number;
  segment: {
    id: number;
    name: string;
    activity_type: string;
    distance: number;
    average_grade: number;
    maximum_grade: number;
    elevation_high: number;
    elevation_low: number;
    start_latlng: [number, number];
    end_latlng: [number, number];
    climb_category: number;
    city: string;
    state: string;
    country: string;
    private: boolean;
    hazardous: boolean;
    starred: boolean;
  };
  kom_rank?: number;
  pr_rank?: number;
  achievements?: any[];
}

export type Activity = {
  achievement_count: number | null;
  activity_type: string | null;
  athlete_count: number | null;
  average_cadence: number | null;
  average_heartrate: number | null;
  average_speed: number | null;
  average_temp: number | null;
  average_watts: number | null;
  calories: number | null;
  comment_count: number | null;
  commute: boolean | null;
  created_at: string | null;
  date: string;
  description: string | null;
  device_name: string | null;
  device_watts: boolean | null;
  display_hide_heartrate_option: boolean | null;
  distance: number | null;
  elapsed_time: number | null;
  elev_high: number | null;
  elev_low: number | null;
  end_latlng: number[] | null;
  flagged: boolean | null;
  has_heartrate: boolean | null;
  has_kudoed: boolean | null;
  has_power_meter: boolean | null;
  heartrate_opt_out: boolean | null;
  id: string;
  kilojoules: number | null;
  kudos_count: number | null;
  location: string | null;
  manual: boolean | null;
  map: any | null;
  max_heartrate: number | null;
  max_speed: number | null;
  max_watts: number | null;
  moving_time: number | null;
  name: string;
  notes: string | null;
  perceived_exertion: number | null;
  photo_count: number | null;
  pr_count: number | null;
  prefer_perceived_exertion: boolean | null;
  private: boolean | null;
  segment_leaderboard_opt_out: boolean | null;
  source: string | null;
  sport_type: string | null;
  start_date: string | null;
  start_latlng: number[] | null;
  strava_gear_id: string | null;
  strava_id: string | null;
  suffer_score: number | null;
  timezone: string | null;
  total_elevation_gain: number | null;
  total_photo_count: number | null;
  trainer: boolean | null;
  type: string;
  unit: string;
  updated_at: string | null;
  upload_id: string | null;
  url: string | null;
  user_id: string;
  value: number;
  weighted_average_watts: number | null;
  workout_type: number | null;
}

export type ActivityInsert = Omit<Activity, 'id' | 'created_at' | 'updated_at'> & { id?: string; created_at?: string | null; updated_at?: string | null; };
export type ActivityUpdate = Partial<Activity>; 